//! Reimagine-owned provider boundary.
//!
//! `AgentProvider` is the trait every concrete provider adapter must
//! implement. The shapes are deliberately friendly to a future
//! Rig-backed OpenAI-compatible and Anthropic adapter, but the agent
//! crate does not depend on Rig, Cersei, or any concrete provider SDK.
//! `complete` and `stream` operate over `AgentRequest`/`AgentResponse`/
//! `AgentStreamEvent` payloads that are provider-agnostic.

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::error::ProviderError;
use crate::ids::{ModelName, ProviderName, agent_id_type};

// Stable, caller-supplied id for a tool call requested by the model.
// Generated by `agent_id_type!` (ids.rs) — same shape as
// `AgentSessionId` / `ToolName`. `AgentTurnId` (turn.rs) still
// hand-rolls this shape pending the same treatment (AC-22, tracked
// with the turn.rs owner).
agent_id_type!(ToolCallId);

/// A single content block in a [`Message`]. V1 supports text and file
/// blocks; file blocks lay the groundwork for image inputs (and other
/// media) with an inline base64 or URL source.
///
/// Serde shape (tagged by `type`):
/// - `{"type":"text","text":"hi"}`
/// - `{"type":"file","media_type":"image/png","source":{...},"filename":"pic.png"}`
///
/// The plain-text `Message.content` of earlier versions is now
/// represented as `Text` blocks; `Message::content()` aggregates them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ContentBlock {
    /// Plain-text content.
    Text(String),
    /// A file (image, audio, ...) referenced by its source.
    File(FileContentBlock),
}

/// A file content block.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileContentBlock {
    /// IANA media type, e.g. `"image/png"`. Required.
    media_type: String,
    /// Where the file data lives.
    source: FileSource,
    /// Optional display filename.
    filename: Option<String>,
}

impl FileContentBlock {
    /// Build a file block backed by an inline base64 payload.
    pub fn data(media_type: impl Into<String>, base64: impl Into<String>) -> Self {
        Self {
            media_type: media_type.into(),
            source: FileSource::Data {
                base64: base64.into(),
            },
            filename: None,
        }
    }

    /// Build a file block referencing a workspace-relative path or URL.
    /// Concrete adapters resolve the reference into an inline base64
    /// payload before wire translation.
    pub fn url(media_type: impl Into<String>, url: impl Into<String>) -> Self {
        Self {
            media_type: media_type.into(),
            source: FileSource::Url(url.into()),
            filename: None,
        }
    }

    pub fn media_type(&self) -> &str {
        &self.media_type
    }

    pub fn source(&self) -> &FileSource {
        &self.source
    }

    pub fn filename(&self) -> Option<&str> {
        self.filename.as_deref()
    }

    /// Replace the source, keeping `media_type` and `filename`. Used by
    /// adapters to resolve workspace-relative `Url` sources into inline
    /// base64 payloads before wire translation.
    pub fn with_source(mut self, source: FileSource) -> Self {
        self.source = source;
        self
    }
}

/// Where a [`FileContentBlock`]'s data lives.
///
/// Serde shape:
/// - `{"type":"data","base64":"..."}` — pure base64, no `data:` prefix
/// - `{"type":"url","url":"..."}` — workspace-relative path or URL
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FileSource {
    /// Inline payload, base64-encoded without a `data:` prefix.
    Data { base64: String },
    /// Workspace-relative path or URL.
    Url(String),
}

impl FileSource {
    /// `Some` for [`FileSource::Data`] — the raw base64 payload.
    pub fn base64(&self) -> Option<&str> {
        match self {
            Self::Data { base64 } => Some(base64),
            Self::Url(_) => None,
        }
    }

    /// `Some` for [`FileSource::Url`] — the path or URL.
    pub fn url(&self) -> Option<&str> {
        match self {
            Self::Url(url) => Some(url),
            Self::Data { .. } => None,
        }
    }
}

impl serde::Serialize for ContentBlock {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        match self {
            Self::Text(text) => {
                let mut state = serializer.serialize_struct("ContentBlock", 2)?;
                state.serialize_field("type", "text")?;
                state.serialize_field("text", text)?;
                state.end()
            }
            Self::File(file) => file.serialize(serializer),
        }
    }
}

impl<'de> serde::Deserialize<'de> for ContentBlock {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(serde::Deserialize)]
        #[serde(tag = "type", rename_all = "snake_case")]
        enum Raw {
            Text { text: String },
            File(FileContentBlock),
        }
        Ok(match Raw::deserialize(deserializer)? {
            Raw::Text { text } => Self::Text(text),
            Raw::File(file) => Self::File(file),
        })
    }
}

impl serde::Serialize for FileContentBlock {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut state = serializer.serialize_struct("FileContentBlock", 4)?;
        state.serialize_field("type", "file")?;
        state.serialize_field("media_type", &self.media_type)?;
        state.serialize_field("source", &self.source)?;
        if let Some(filename) = &self.filename {
            state.serialize_field("filename", filename)?;
        }
        state.end()
    }
}

impl<'de> serde::Deserialize<'de> for FileContentBlock {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(serde::Deserialize)]
        #[serde(rename_all = "snake_case")]
        struct Raw {
            media_type: String,
            source: FileSource,
            filename: Option<String>,
        }
        let raw = Raw::deserialize(deserializer)?;
        Ok(Self {
            media_type: raw.media_type,
            source: raw.source,
            filename: raw.filename,
        })
    }
}

impl serde::Serialize for FileSource {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut state = serializer.serialize_struct("FileSource", 2)?;
        match self {
            Self::Data { base64 } => {
                state.serialize_field("type", "data")?;
                state.serialize_field("base64", base64)?;
            }
            Self::Url(url) => {
                state.serialize_field("type", "url")?;
                state.serialize_field("url", url)?;
            }
        }
        state.end()
    }
}

impl<'de> serde::Deserialize<'de> for FileSource {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(serde::Deserialize)]
        #[serde(tag = "type", rename_all = "snake_case")]
        enum Raw {
            Data { base64: String },
            Url { url: String },
        }
        Ok(match Raw::deserialize(deserializer)? {
            Raw::Data { base64 } => Self::Data { base64 },
            Raw::Url { url } => Self::Url(url),
        })
    }
}

/// Provider-agnostic chat message.
///
/// Content is a list of [`ContentBlock`]s (text and file blocks), giving
/// the model a structured view of multimodal input. `content()` is the
/// convenience text projection of the blocks; wire translations consume
/// it for text-only flows and should walk `blocks()` once a given
/// adapter carries file blocks to the provider.
///
/// Serde format changed from the V1 plain-string shape: content now
/// serializes as a block array. Files persisted before this change fail
/// to deserialize — development-period format change, no migration.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Message {
    /// Role discriminator. V1 uses the conventional string names
    /// `"system"`, `"user"`, `"assistant"`, and `"tool"`. Provider
    /// adapters translate to OpenAI / Anthropic roles.
    role: String,
    /// Message content blocks.
    content: Vec<ContentBlock>,
    /// Cached aggregation of the `Text` blocks (joined with `\n`) so
    /// `content()` can return a `&str` without allocation. A pure
    /// function of `content`; skipped by serde.
    #[serde(skip)]
    content_text: String,
    /// Optional tool call id this message is responding to (for role =
    /// "tool").
    tool_call_id: Option<ToolCallId>,
    /// Optional tool calls the assistant is making (for role =
    /// "assistant").
    tool_calls: Vec<ToolCall>,
}

impl Message {
    /// Aggregated text of the given blocks: all `Text` blocks joined
    /// with `\n`, or the empty string when there are no text blocks.
    fn aggregate_text(blocks: &[ContentBlock]) -> String {
        blocks
            .iter()
            .filter_map(|block| match block {
                ContentBlock::Text(text) => Some(text.as_str()),
                ContentBlock::File(_) => None,
            })
            .collect::<Vec<&str>>()
            .join("\n")
    }

    fn from_parts(
        role: impl Into<String>,
        content: Vec<ContentBlock>,
        tool_call_id: Option<ToolCallId>,
        tool_calls: Vec<ToolCall>,
    ) -> Self {
        let content_text = Self::aggregate_text(&content);
        Self {
            role: role.into(),
            content,
            content_text,
            tool_call_id,
            tool_calls,
        }
    }

    pub fn system(content: impl Into<String>) -> Self {
        Self::from_parts(
            "system",
            vec![ContentBlock::Text(content.into())],
            None,
            Vec::new(),
        )
    }

    pub fn user(content: impl Into<String>) -> Self {
        Self::from_parts(
            "user",
            vec![ContentBlock::Text(content.into())],
            None,
            Vec::new(),
        )
    }

    pub fn assistant(content: impl Into<String>) -> Self {
        Self::from_parts(
            "assistant",
            vec![ContentBlock::Text(content.into())],
            None,
            Vec::new(),
        )
    }

    /// Build a `tool` message that delivers `content` as the result of
    /// the tool call with id `tool_call_id`.
    pub fn tool_result(tool_call_id: ToolCallId, content: impl Into<String>) -> Self {
        Self::from_parts(
            "tool",
            vec![ContentBlock::Text(content.into())],
            Some(tool_call_id),
            Vec::new(),
        )
    }

    /// Construct an assistant message that calls one or more tools.
    pub fn assistant_with_tool_calls(
        content: impl Into<String>,
        tool_calls: Vec<ToolCall>,
    ) -> Self {
        Self::from_parts(
            "assistant",
            vec![ContentBlock::Text(content.into())],
            None,
            tool_calls,
        )
    }

    /// Build a `user` message from explicit content blocks (e.g. text
    /// plus file blocks for image inputs).
    pub fn user_with_blocks(blocks: Vec<ContentBlock>) -> Self {
        Self::from_parts("user", blocks, None, Vec::new())
    }

    pub fn role(&self) -> &str {
        &self.role
    }

    /// Aggregated text of the message: all `Text` blocks joined with
    /// `\n`, or the empty string when there are no text blocks.
    pub fn content(&self) -> &str {
        &self.content_text
    }

    /// The message's content blocks, in order.
    pub fn blocks(&self) -> &[ContentBlock] {
        &self.content
    }

    /// Replace the content blocks, preserving role, `tool_call_id`, and
    /// tool calls. Recomputes the cached text aggregation. Used by
    /// adapters that rewrite file block sources before wire
    /// translation.
    pub fn with_blocks(mut self, blocks: Vec<ContentBlock>) -> Self {
        self.content_text = Self::aggregate_text(&blocks);
        self.content = blocks;
        self
    }

    pub fn tool_call_id(&self) -> Option<&ToolCallId> {
        self.tool_call_id.as_ref()
    }

    pub fn tool_calls(&self) -> &[ToolCall] {
        &self.tool_calls
    }
}

impl<'de> serde::Deserialize<'de> for Message {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(serde::Deserialize)]
        struct Raw {
            role: String,
            content: Vec<ContentBlock>,
            tool_call_id: Option<ToolCallId>,
            tool_calls: Vec<ToolCall>,
        }
        let raw = Raw::deserialize(deserializer)?;
        Ok(Self::from_parts(
            raw.role,
            raw.content,
            raw.tool_call_id,
            raw.tool_calls,
        ))
    }
}

/// Tool call requested by the model. The `arguments` payload is raw JSON
/// so providers and tools can negotiate the exact shape.
#[derive(Debug, Clone, PartialEq, Hash, Serialize, Deserialize)]
pub struct ToolCall {
    id: ToolCallId,
    /// Name of the tool the model wants to invoke. The agent runtime
    /// looks this up in the registry.
    name: String,
    /// JSON arguments for the tool, kept as a `serde_json::Value` so
    /// the registry can deserialize into the tool's input shape.
    arguments: Value,
}

impl ToolCall {
    pub fn new(id: ToolCallId, name: impl Into<String>, arguments: Value) -> Self {
        Self {
            id,
            name: name.into(),
            arguments,
        }
    }

    pub fn id(&self) -> &ToolCallId {
        &self.id
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn arguments(&self) -> &Value {
        &self.arguments
    }
}

/// Token-usage report from a provider. Optional, but every concrete
/// adapter should report usage when the upstream API does.
///
/// `reasoning_tokens` counts the tokens the model spent on internal
/// reasoning before answering (OpenAI `output_tokens_details.reasoning_tokens`,
/// DeepSeek-style top-level `reasoning_tokens`). It is a sub-portion of
/// `output_tokens`.
///
/// Cache accounting follows the Anthropic SDK budget convention that
/// CM-V2's budget model consumes directly:
/// `total = input + cache_creation + cache_read + output`. OpenAI reports
/// only a combined `cached_tokens` (read from `input_tokens_details`),
/// which is mapped into `cache_read_input_tokens`.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Usage {
    input_tokens: Option<u64>,
    output_tokens: Option<u64>,
    #[serde(default)]
    reasoning_tokens: Option<u64>,
    /// Tokens written to the provider cache (Anthropic
    /// `cache_creation_input_tokens`). OpenAI has no equivalent.
    #[serde(default)]
    cache_creation_input_tokens: Option<u64>,
    /// Tokens read from the provider cache (Anthropic
    /// `cache_read_input_tokens`; OpenAI `input_tokens_details.cached_tokens`).
    #[serde(default)]
    cache_read_input_tokens: Option<u64>,
}

impl Usage {
    pub fn new(input_tokens: Option<u64>, output_tokens: Option<u64>) -> Self {
        Self {
            input_tokens,
            output_tokens,
            reasoning_tokens: None,
            cache_creation_input_tokens: None,
            cache_read_input_tokens: None,
        }
    }

    pub fn with_reasoning_tokens(mut self, reasoning_tokens: Option<u64>) -> Self {
        self.reasoning_tokens = reasoning_tokens;
        self
    }

    pub fn with_cache_creation(mut self, tokens: Option<u64>) -> Self {
        self.cache_creation_input_tokens = tokens;
        self
    }

    pub fn with_cache_read(mut self, tokens: Option<u64>) -> Self {
        self.cache_read_input_tokens = tokens;
        self
    }

    /// Merge another usage sample into this one, accumulating each
    /// token bucket (AR-29). `None` buckets remain `None` unless the
    /// incoming sample carries a value.
    pub fn merge(&mut self, other: Usage) {
        self.input_tokens = Self::add_or(other.input_tokens, self.input_tokens);
        self.output_tokens = Self::add_or(other.output_tokens, self.output_tokens);
        self.reasoning_tokens = Self::add_or(other.reasoning_tokens, self.reasoning_tokens);
        self.cache_creation_input_tokens = Self::add_or(
            other.cache_creation_input_tokens,
            self.cache_creation_input_tokens,
        );
        self.cache_read_input_tokens =
            Self::add_or(other.cache_read_input_tokens, self.cache_read_input_tokens);
    }

    fn add_or(a: Option<u64>, b: Option<u64>) -> Option<u64> {
        match (a, b) {
            (Some(x), Some(y)) => Some(x + y),
            (Some(x), None) => Some(x),
            (None, Some(y)) => Some(y),
            (None, None) => None,
        }
    }

    pub fn input_tokens(&self) -> Option<u64> {
        self.input_tokens
    }

    pub fn output_tokens(&self) -> Option<u64> {
        self.output_tokens
    }

    pub fn reasoning_tokens(&self) -> Option<u64> {
        self.reasoning_tokens
    }

    pub fn cache_creation_input_tokens(&self) -> Option<u64> {
        self.cache_creation_input_tokens
    }

    pub fn cache_read_input_tokens(&self) -> Option<u64> {
        self.cache_read_input_tokens
    }

    /// Total budgeted tokens: input + cache_creation + cache_read + output
    /// (Anthropic SDK convention). `None` when no token count is reported
    /// at all.
    ///
    /// NOTE: OpenAI reports `cached_tokens` as a sub-portion of
    /// `prompt_tokens`, so for OpenAI sources this formula counts the
    /// cached tokens twice (input already includes them). The convention
    /// is exact for Anthropic; CM-V2 consumers must not mix providers
    /// when comparing totals.
    pub fn total(&self) -> Option<u64> {
        let any_reported = [
            self.input_tokens,
            self.output_tokens,
            self.cache_creation_input_tokens,
            self.cache_read_input_tokens,
        ]
        .iter()
        .any(Option::is_some);
        if !any_reported {
            return None;
        }
        Some(
            self.input_tokens.unwrap_or(0)
                + self.cache_creation_input_tokens.unwrap_or(0)
                + self.cache_read_input_tokens.unwrap_or(0)
                + self.output_tokens.unwrap_or(0),
        )
    }
}

/// Token pricing for a model in USD per 1M tokens. Fields are
/// optional-by-default so catalog entries with partial pricing remain
/// usable.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Default)]
pub struct ModelCost {
    input: f64,
    output: f64,
    cache_read: f64,
    cache_write: f64,
}

impl ModelCost {
    pub fn new(input: f64, output: f64, cache_read: f64, cache_write: f64) -> Self {
        Self {
            input,
            output,
            cache_read,
            cache_write,
        }
    }

    pub fn input(&self) -> f64 {
        self.input
    }

    pub fn output(&self) -> f64 {
        self.output
    }

    pub fn cache_read(&self) -> f64 {
        self.cache_read
    }

    pub fn cache_write(&self) -> f64 {
        self.cache_write
    }
}

/// Information about a single model advertised by a provider.
///
/// Capability fields beyond `capabilities` (reasoning, input
/// modalities, context window, max tokens, cost) default to their
/// "unknown" value so older serialized payloads deserialize without
/// breaking.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModelInfo {
    name: ModelName,
    /// Provider that owns this model. Optional because some catalogs
    /// are queried per provider.
    provider: Option<ProviderName>,
    capabilities: Vec<ModelCapability>,
    /// Whether the model performs reasoning before answering.
    #[serde(default)]
    reasoning: bool,
    /// Input modality names the model accepts (e.g. "text", "image").
    #[serde(default)]
    input_modalities: Vec<String>,
    /// Model context window in tokens.
    #[serde(default)]
    context_window: Option<usize>,
    /// Maximum output tokens the model can produce.
    #[serde(default)]
    max_tokens: Option<usize>,
    /// Token pricing in USD per 1M tokens.
    #[serde(default)]
    cost: Option<ModelCost>,
}

impl ModelInfo {
    pub fn new(name: ModelName) -> Self {
        Self {
            name,
            provider: None,
            capabilities: Vec::new(),
            reasoning: false,
            input_modalities: Vec::new(),
            context_window: None,
            max_tokens: None,
            cost: None,
        }
    }

    pub fn with_provider(mut self, provider: ProviderName) -> Self {
        self.provider = Some(provider);
        self
    }

    pub fn with_capability(mut self, cap: ModelCapability) -> Self {
        self.capabilities.push(cap);
        self
    }

    pub fn with_capabilities(mut self, caps: impl IntoIterator<Item = ModelCapability>) -> Self {
        self.capabilities.extend(caps);
        self
    }

    pub fn with_reasoning(mut self, reasoning: bool) -> Self {
        self.reasoning = reasoning;
        self
    }

    pub fn with_input_modalities(mut self, modalities: impl IntoIterator<Item = String>) -> Self {
        self.input_modalities.extend(modalities);
        self
    }

    pub fn with_context_window(mut self, tokens: Option<usize>) -> Self {
        self.context_window = tokens;
        self
    }

    pub fn with_max_tokens(mut self, tokens: Option<usize>) -> Self {
        self.max_tokens = tokens;
        self
    }

    pub fn with_cost(mut self, cost: Option<ModelCost>) -> Self {
        self.cost = cost;
        self
    }

    pub fn name(&self) -> &ModelName {
        &self.name
    }

    pub fn provider(&self) -> Option<&ProviderName> {
        self.provider.as_ref()
    }

    pub fn capabilities(&self) -> &[ModelCapability] {
        &self.capabilities
    }

    pub fn reasoning(&self) -> bool {
        self.reasoning
    }

    pub fn input_modalities(&self) -> &[String] {
        &self.input_modalities
    }

    pub fn context_window(&self) -> Option<usize> {
        self.context_window
    }

    pub fn max_tokens(&self) -> Option<usize> {
        self.max_tokens
    }

    pub fn cost(&self) -> Option<&ModelCost> {
        self.cost.as_ref()
    }
}

/// Model capability hints surfaced by the provider. The set is
/// deliberately small in V1; provider adapters are free to advertise
/// only what the upstream API exposes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModelCapability {
    Chat,
    ToolUse,
    Vision,
    Streaming,
}

impl ModelCapability {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Chat => "chat",
            Self::ToolUse => "tool_use",
            Self::Vision => "vision",
            Self::Streaming => "streaming",
        }
    }
}

impl std::fmt::Display for ModelCapability {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Request to a provider. Provider-agnostic on purpose so future
/// Rig-backed OpenAI-compatible and Anthropic adapters can serialize to
/// their native wire formats.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentRequest {
    model: ModelName,
    messages: Vec<Message>,
    /// Optional tools to advertise. Concrete adapters translate to
    /// OpenAI's `tools` or Anthropic's `tools` blocks.
    tools: Vec<AgentToolDefinition>,
    /// Provider-specific options blob, kept opaque at the boundary.
    options: Value,
}

impl AgentRequest {
    pub fn new(model: ModelName, messages: Vec<Message>) -> Self {
        Self {
            model,
            messages,
            tools: Vec::new(),
            options: Value::Null,
        }
    }

    pub fn with_tools(mut self, tools: Vec<AgentToolDefinition>) -> Self {
        self.tools = tools;
        self
    }

    pub fn with_options(mut self, options: Value) -> Self {
        self.options = options;
        self
    }

    pub fn model(&self) -> &ModelName {
        &self.model
    }

    pub fn messages(&self) -> &[Message] {
        &self.messages
    }

    pub fn tools(&self) -> &[AgentToolDefinition] {
        &self.tools
    }

    pub fn options(&self) -> &Value {
        &self.options
    }
}

/// Tool definition sent to the provider. The shape is provider-agnostic
/// (name, description, and a JSON-Schema for arguments) so adapters can
/// translate to OpenAI function-calling or Anthropic tool-use without
/// coupling the agent crate to either schema.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentToolDefinition {
    name: String,
    description: String,
    /// JSON Schema describing the tool's input shape.
    parameters: Value,
}

impl AgentToolDefinition {
    pub fn new(name: impl Into<String>, description: impl Into<String>, parameters: Value) -> Self {
        Self {
            name: name.into(),
            description: description.into(),
            parameters,
        }
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn description(&self) -> &str {
        &self.description
    }

    pub fn parameters(&self) -> &Value {
        &self.parameters
    }
}

/// Provider-agnostic response. Carries the assistant message, optional
/// usage report, and an optional `stop_reason` describing why the model
/// stopped (e.g. end-of-turn vs. tool use).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentResponse {
    message: Message,
    usage: Option<Usage>,
    stop_reason: Option<String>,
}

impl AgentResponse {
    pub fn new(message: Message) -> Self {
        Self {
            message,
            usage: None,
            stop_reason: None,
        }
    }

    pub fn with_usage(mut self, usage: Usage) -> Self {
        self.usage = Some(usage);
        self
    }

    pub fn with_stop_reason(mut self, reason: impl Into<String>) -> Self {
        self.stop_reason = Some(reason.into());
        self
    }

    pub fn message(&self) -> &Message {
        &self.message
    }

    pub fn usage(&self) -> Option<&Usage> {
        self.usage.as_ref()
    }

    pub fn stop_reason(&self) -> Option<&str> {
        self.stop_reason.as_deref()
    }
}

/// Streamed event from a provider. The agent runtime consumes these to
/// surface incremental progress to the host (Tauri / Axum / tests).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum AgentStreamEvent {
    /// A token-sized content delta for the assistant message.
    ContentDelta(String),
    /// A token-sized delta of the model's reasoning / thinking text.
    /// Emitted before content for models that reason (OpenAI
    /// `reasoning_content`, Responses `reasoning_summary_text.delta`,
    /// Anthropic `thinking_delta`). The agent runtime surfaces these to
    /// hosts for display but never replays them into the message
    /// history — reasoning is display-only in V2 (encrypted reasoning
    /// is excluded entirely).
    ReasoningDelta(String),
    /// A complete tool call the model wants to make. Providers that
    /// stream tool calls incrementally may emit one or more
    /// `ToolCallDelta` events first; the runtime only acts on the
    /// complete `ToolCall` — deltas are informational and currently
    /// ignored by the loop.
    ToolCall(ToolCall),
    /// A partial tool call. `index` is the position in the final
    /// tool-call list. `id`, `name`, and `arguments_delta` are optional
    /// because providers may stream them at different times.
    ToolCallDelta {
        index: u32,
        id: Option<ToolCallId>,
        name: Option<String>,
        arguments_delta: Option<String>,
    },
    /// Final usage report. Optional because not every provider surfaces
    /// usage in the stream.
    Usage(Usage),
    /// Server-side compaction notification (OpenAI Responses API):
    /// the provider replaced earlier conversation items with an
    /// opaque compaction item. `item_id` identifies it. Informational
    /// for the runtime — the compacted content is not human-readable
    /// and is never replayed into history (CM-V2e, PV-01b reserved
    /// channel).
    Compacted { item_id: String },
    /// A transport-level failure occurred while reading the stream
    /// (e.g. the connection dropped mid-response). The harness stops
    /// the turn with a provider error (AC-05); the message is
    /// host-visible diagnostics.
    Error(String),
    /// A host-visible informational warning from the provider (e.g. a
    /// stream ended with incomplete tool-call fragments, D-5). Unlike
    /// [`AgentStreamEvent::Error`], this is NOT terminal: the harness
    /// logs it and continues the turn.
    Warning(String),
    /// Stream completed; the runtime stops reading.
    Done { stop_reason: Option<String> },
}

impl AgentStreamEvent {
    /// `true` for the terminal `Done` event.
    pub fn is_done(&self) -> bool {
        matches!(self, Self::Done { .. })
    }
}

/// Reimagine-owned provider trait.
///
/// Implementors adapt a specific upstream API (OpenAI-compatible,
/// Anthropic, future Rig-backed) to the agent runtime. Implementations
/// may be sync internally but expose async methods so the runtime can
/// compose them with other async services.
#[async_trait]
pub trait AgentProvider: Send + Sync {
    /// Provider identity. Used for diagnostics, audit, and for
    /// `list_models` payloads.
    fn name(&self) -> ProviderName;

    /// Send a single completion request. Returns the provider's full
    /// response, or a `ProviderError` on transport / API failure.
    async fn complete(&self, request: AgentRequest) -> Result<AgentResponse, ProviderError>;

    /// Stream a completion. Implementations are expected to return
    /// events in the order the upstream produces them, terminating with
    /// `AgentStreamEvent::Done`.
    async fn stream(&self, request: AgentRequest) -> Result<Box<dyn AgentStream>, ProviderError>;

    /// List the models this provider advertises. V1 expects this to be
    /// cheap; if the upstream needs an async call, implementations may
    /// cache internally.
    async fn list_models(&self) -> Result<Vec<ModelInfo>, ProviderError>;
}

/// Stream of provider events returned by `AgentProvider::stream`.
///
/// The trait intentionally exposes a single operation — pull the next
/// event. Diagnostics and cancellation are handled by the harness loop
/// between reads; adapters terminate the stream with `None` or a final
/// `AgentStreamEvent::Done`.
#[async_trait]
pub trait AgentStream: Send {
    /// Pull the next event. Returns `None` when the stream is
    /// exhausted; concrete adapters translate the upstream's "done"
    /// signal into either `None` or a final `AgentStreamEvent::Done`.
    async fn next_event(&mut self) -> Option<AgentStreamEvent>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn message_role_helpers() {
        let m = Message::system("you are a helpful assistant");
        assert_eq!(m.role(), "system");
        assert_eq!(m.content(), "you are a helpful assistant");

        let tool_id = ToolCallId::new("call-1");
        let m = Message::tool_result(tool_id.clone(), "ok");
        assert_eq!(m.role(), "tool");
        assert_eq!(m.tool_call_id(), Some(&tool_id));

        let call = ToolCall::new(ToolCallId::new("c1"), "echo", json!({"x": 1}));
        let m = Message::assistant_with_tool_calls("", vec![call.clone()]);
        assert_eq!(m.tool_calls().len(), 1);
        assert_eq!(m.tool_calls()[0], call);
    }

    #[test]
    fn tool_call_hashes_equal_for_equal_values() {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::{Hash, Hasher};

        fn hash_of(call: &ToolCall) -> u64 {
            let mut hasher = DefaultHasher::new();
            call.hash(&mut hasher);
            hasher.finish()
        }

        let a = ToolCall::new(ToolCallId::new("c1"), "echo", json!({"x": 1}));
        let b = ToolCall::new(ToolCallId::new("c1"), "echo", json!({"x": 1}));
        let different_id = ToolCall::new(ToolCallId::new("c2"), "echo", json!({"x": 1}));
        assert_eq!(hash_of(&a), hash_of(&b));
        assert_ne!(hash_of(&a), hash_of(&different_id));
    }

    #[test]
    fn request_response_shapes_roundtrip() {
        let model = ModelName::new("gpt-4o-mini");
        let req = AgentRequest::new(model.clone(), vec![Message::user("hi")])
            .with_tools(vec![AgentToolDefinition::new(
                "echo",
                "echo",
                json!({"type": "object"}),
            )])
            .with_options(json!({"temperature": 0.0}));
        assert_eq!(req.model(), &model);
        assert_eq!(req.messages().len(), 1);
        assert_eq!(req.tools().len(), 1);
        assert_eq!(req.options(), &json!({"temperature": 0.0}));

        let resp = AgentResponse::new(Message::assistant("hello"))
            .with_usage(Usage::new(Some(10), Some(20)))
            .with_stop_reason("end_turn");
        assert_eq!(resp.usage().unwrap().input_tokens(), Some(10));
        assert_eq!(resp.stop_reason(), Some("end_turn"));
    }

    #[test]
    fn model_info_carries_provider_and_capabilities() {
        let info = ModelInfo::new(ModelName::new("gpt-4o-mini"))
            .with_provider(ProviderName::new("openai"))
            .with_capabilities([ModelCapability::Chat, ModelCapability::ToolUse]);
        assert_eq!(info.provider().unwrap().as_str(), "openai");
        assert_eq!(info.capabilities().len(), 2);
    }

    #[test]
    fn stream_event_done_predicate() {
        assert!(AgentStreamEvent::Done { stop_reason: None }.is_done());
        assert!(!AgentStreamEvent::ContentDelta("hi".into()).is_done());
    }

    #[test]
    fn content_block_text_roundtrips() {
        let value = json!({ "type": "text", "text": "hi" });
        let block: ContentBlock = serde_json::from_value(value.clone()).unwrap();
        assert_eq!(block, ContentBlock::Text("hi".into()));
        assert_eq!(serde_json::to_value(&block).unwrap(), value);
    }

    #[test]
    fn content_block_file_data_roundtrips() {
        let value = json!({
            "type": "file",
            "media_type": "image/png",
            "source": { "type": "data", "base64": "iVBORw0KGgo=" },
            "filename": "pic.png",
        });
        let block: ContentBlock = serde_json::from_value(value.clone()).unwrap();
        let ContentBlock::File(file) = &block else {
            panic!("expected file block");
        };
        assert_eq!(file.media_type(), "image/png");
        assert_eq!(file.source().base64(), Some("iVBORw0KGgo="));
        assert_eq!(file.source().url(), None);
        assert_eq!(file.filename(), Some("pic.png"));
        assert_eq!(serde_json::to_value(&block).unwrap(), value);
    }

    #[test]
    fn content_block_file_url_roundtrips() {
        let value = json!({
            "type": "file",
            "media_type": "image/jpeg",
            "source": { "type": "url", "url": "refs/photo.jpg" },
        });
        let block: ContentBlock = serde_json::from_value(value.clone()).unwrap();
        let ContentBlock::File(file) = &block else {
            panic!("expected file block");
        };
        assert_eq!(file.source().url(), Some("refs/photo.jpg"));
        assert_eq!(file.source().base64(), None);
        assert_eq!(file.filename(), None);
        assert_eq!(serde_json::to_value(&block).unwrap(), value);
    }

    #[test]
    fn file_data_constructor_builds_data_source() {
        let file = FileContentBlock::data("image/png", "AAAA");
        assert_eq!(file.media_type(), "image/png");
        assert_eq!(file.source().base64(), Some("AAAA"));
        assert_eq!(file.filename(), None);
    }

    #[test]
    fn file_url_constructor_builds_url_source() {
        let file = FileContentBlock::url("image/png", "refs/pic.png");
        assert_eq!(file.media_type(), "image/png");
        assert_eq!(file.source().url(), Some("refs/pic.png"));
        assert_eq!(file.source().base64(), None);
    }

    #[test]
    fn file_with_source_replaces_source_keeping_metadata() {
        let file = FileContentBlock::data("image/png", "AAAA")
            .with_source(FileSource::Url("refs/pic.png".to_string()));
        assert_eq!(file.source().url(), Some("refs/pic.png"));
        let file = file.with_source(FileSource::Data {
            base64: "BBBB".to_string(),
        });
        assert_eq!(file.media_type(), "image/png");
        assert_eq!(file.source().base64(), Some("BBBB"));
    }

    #[test]
    fn message_with_blocks_replaces_blocks_and_recomputes_text() {
        let message = Message::user_with_blocks(vec![
            ContentBlock::Text("first".into()),
            ContentBlock::File(FileContentBlock::data("image/png", "AAAA")),
        ]);
        assert_eq!(message.content(), "first");
        let replaced = message.with_blocks(vec![
            ContentBlock::Text("third".into()),
            ContentBlock::File(FileContentBlock::data("image/png", "BBBB")),
        ]);
        assert_eq!(replaced.role(), "user");
        assert_eq!(replaced.content(), "third");
        assert_eq!(replaced.blocks().len(), 2);
        let ContentBlock::File(file) = &replaced.blocks()[1] else {
            panic!("expected file block");
        };
        assert_eq!(file.source().base64(), Some("BBBB"));
    }

    #[test]
    fn content_aggregates_text_blocks() {
        let message = Message::user_with_blocks(vec![
            ContentBlock::Text("first".into()),
            ContentBlock::File(FileContentBlock::data("image/png", "AAAA")),
            ContentBlock::Text("second".into()),
        ]);
        assert_eq!(message.content(), "first\nsecond");
        assert_eq!(message.blocks().len(), 3);
    }

    #[test]
    fn content_without_text_blocks_is_empty() {
        let message = Message::user_with_blocks(vec![ContentBlock::File(FileContentBlock::data(
            "image/png",
            "AAAA",
        ))]);
        assert_eq!(message.content(), "");
        assert_eq!(message.blocks().len(), 1);
    }

    #[test]
    fn user_with_blocks_builds_user_message() {
        let message = Message::user_with_blocks(vec![ContentBlock::Text("hi".into())]);
        assert_eq!(message.role(), "user");
        assert_eq!(message.blocks(), &[ContentBlock::Text("hi".into())]);
    }

    #[test]
    fn message_roundtrips_content_blocks() {
        let message = Message::user_with_blocks(vec![
            ContentBlock::Text("describe".into()),
            ContentBlock::File(FileContentBlock::data("image/png", "AAAA")),
        ]);
        let value = serde_json::to_value(&message).unwrap();
        let restored: Message = serde_json::from_value(value).unwrap();
        assert_eq!(restored, message);
        assert_eq!(restored.content(), "describe");
        assert_eq!(restored.blocks().len(), 2);
    }

    #[test]
    fn old_string_content_format_fails_to_deserialize() {
        // Development-period format change: the V1 `{"content":"hi"}`
        // string shape is intentionally not supported anymore.
        let result = serde_json::from_str::<Message>(
            r#"{"role":"user","content":"hi","tool_call_id":null,"tool_calls":[]}"#,
        );
        assert!(result.is_err());
    }
}
