/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AssetsRouteImport } from "./routes/assets"
import { Route as ModelsRouteImport } from "./routes/models"
import { Route as NewRouteImport } from "./routes/new"
import { Route as RunsRouteImport } from "./routes/runs"
import { Route as SettingsRouteImport } from "./routes/settings"

const AssetsRoute = AssetsRouteImport.update({
  id: "/assets",
  path: "/assets",
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: "/runs",
  path: "/runs",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/assets": typeof AssetsRoute
  "/models": typeof ModelsRoute
  "/new": typeof NewRoute
  "/runs": typeof RunsRoute
  "/settings": typeof SettingsRoute
}
export interface FileRoutesByTo {
  "/assets": typeof AssetsRoute
  "/models": typeof ModelsRoute
  "/new": typeof NewRoute
  "/runs": typeof RunsRoute
  "/settings": typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/assets": typeof AssetsRoute
  "/models": typeof ModelsRoute
  "/new": typeof NewRoute
  "/runs": typeof RunsRoute
  "/settings": typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/assets" | "/models" | "/new" | "/runs" | "/settings"
  fileRoutesByTo: FileRoutesByTo
  to: "/assets" | "/models" | "/new" | "/runs" | "/settings"
  id: "__root__" | "/assets" | "/models" | "/new" | "/runs" | "/settings"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AssetsRoute: typeof AssetsRoute
  ModelsRoute: typeof ModelsRoute
  NewRoute: typeof NewRoute
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/assets": {
      id: "/assets"
      path: "/assets"
      fullPath: "/assets"
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/models": {
      id: "/models"
      path: "/models"
      fullPath: "/models"
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/new": {
      id: "/new"
      path: "/new"
      fullPath: "/new"
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/runs": {
      id: "/runs"
      path: "/runs"
      fullPath: "/runs"
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AssetsRoute: AssetsRoute,
  ModelsRoute: ModelsRoute,
  NewRoute: NewRoute,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
