[package]
name = "reimagine-backend-worker-transport-grpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
futures-core = "0.3"
prost = "0.14"
rcgen = "0.13"
reimagine-backend-worker-protocol = { path = "../backend-worker-protocol" }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["io-util", "rt", "sync", "time"] }
tokio-stream = "0.1"
tonic = { version = "0.14", features = ["transport", "tls-ring"] }
tonic-prost = "0.14"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-prost-build = "0.14"
