[package]
name = "reimagine-backend-worker-transport-grpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
prost = "0.14"
reimagine-backend-worker-protocol = { path = "../backend-worker-protocol" }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["io-util", "rt", "sync", "time"] }
tonic = "0.14"
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
